services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # REST
      - "6334:6334"   # gRPC
    volumes:
      - ${HOME}/source/data/qdrant_storage:/qdrant/storage
      - ${HOME}/source/data/qdrant_snapshots:/qdrant/snapshots
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:6333/collections >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s






